package cs455.overlay.node;

import cs455.overlay.wireformats.Event;

/***
 * Interface for the nodes. 
 * 
 * Requires an onEvent method that allows the receiver to send information to the nodes.
 * 
 * @author acarbona
 *
 */
public interface Node {
	/***
	 * onEvent parses the Event generated by the receiver thread.
	 * Depending on the node, it will only parse certain events.
	 * 
	 * @param e Event to parse
	 */
	public void onEvent(Event e);
}
